# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1d0339ae66b962b3af9bc925da65ea34daa47ac363282fa789956f667938fef2f1e824d054cbb005758f257c5339c66bd8d075df6e34fe79a8511f1b631a85

test:
  secret_key_base: e70baa57271b547412fcddd6cbe785bd6137d4da720196546cb540d674ff5c073ff3628763810bb0247cd0d4f1fce28fce6129b6a90300d37d94f2cd290392cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
